// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/domain.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/domain.go -destination=internal/domain/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "sessionproxy/internal/domain"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, u domain.User) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, u)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, u)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockUserRepository) List(ctx context.Context, limit, offset int) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), ctx, limit, offset)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, u domain.User) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, u)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, u)
}

// MockDeviceRepository is a mock of DeviceRepository interface.
type MockDeviceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceRepositoryMockRecorder is the mock recorder for MockDeviceRepository.
type MockDeviceRepositoryMockRecorder struct {
	mock *MockDeviceRepository
}

// NewMockDeviceRepository creates a new mock instance.
func NewMockDeviceRepository(ctrl *gomock.Controller) *MockDeviceRepository {
	mock := &MockDeviceRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceRepository) EXPECT() *MockDeviceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeviceRepository) Create(ctx context.Context, d domain.Device) (domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, d)
	ret0, _ := ret[0].(domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDeviceRepositoryMockRecorder) Create(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceRepository)(nil).Create), ctx, d)
}

// Delete mocks base method.
func (m *MockDeviceRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockDeviceRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeviceRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeviceRepository)(nil).GetByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockDeviceRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockDeviceRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockDeviceRepository)(nil).ListByUser), ctx, userID)
}

// MockAPIKeyRepository is a mock of APIKeyRepository interface.
type MockAPIKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyRepositoryMockRecorder
	isgomock struct{}
}

// MockAPIKeyRepositoryMockRecorder is the mock recorder for MockAPIKeyRepository.
type MockAPIKeyRepositoryMockRecorder struct {
	mock *MockAPIKeyRepository
}

// NewMockAPIKeyRepository creates a new mock instance.
func NewMockAPIKeyRepository(ctrl *gomock.Controller) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{ctrl: ctrl}
	mock.recorder = &MockAPIKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAPIKeyRepository) Create(ctx context.Context, k domain.APIKey) (domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, k)
	ret0, _ := ret[0].(domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAPIKeyRepositoryMockRecorder) Create(ctx, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAPIKeyRepository)(nil).Create), ctx, k)
}

// GetByHash mocks base method.
func (m *MockAPIKeyRepository) GetByHash(ctx context.Context, keyHash string) (domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", ctx, keyHash)
	ret0, _ := ret[0].(domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockAPIKeyRepositoryMockRecorder) GetByHash(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockAPIKeyRepository)(nil).GetByHash), ctx, keyHash)
}

// ListByUser mocks base method.
func (m *MockAPIKeyRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]domain.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockAPIKeyRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockAPIKeyRepository)(nil).ListByUser), ctx, userID)
}

// Revoke mocks base method.
func (m *MockAPIKeyRepository) Revoke(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockAPIKeyRepositoryMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockAPIKeyRepository)(nil).Revoke), ctx, id)
}

// MockTargetSiteRepository is a mock of TargetSiteRepository interface.
type MockTargetSiteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTargetSiteRepositoryMockRecorder
	isgomock struct{}
}

// MockTargetSiteRepositoryMockRecorder is the mock recorder for MockTargetSiteRepository.
type MockTargetSiteRepositoryMockRecorder struct {
	mock *MockTargetSiteRepository
}

// NewMockTargetSiteRepository creates a new mock instance.
func NewMockTargetSiteRepository(ctrl *gomock.Controller) *MockTargetSiteRepository {
	mock := &MockTargetSiteRepository{ctrl: ctrl}
	mock.recorder = &MockTargetSiteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetSiteRepository) EXPECT() *MockTargetSiteRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTargetSiteRepository) Create(ctx context.Context, s domain.TargetSite) (domain.TargetSite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(domain.TargetSite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTargetSiteRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTargetSiteRepository)(nil).Create), ctx, s)
}

// GetByID mocks base method.
func (m *MockTargetSiteRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.TargetSite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.TargetSite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTargetSiteRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTargetSiteRepository)(nil).GetByID), ctx, id)
}

// GetOrCreateByDomain mocks base method.
func (m *MockTargetSiteRepository) GetOrCreateByDomain(ctx context.Context, arg1, name, baseURL string) (domain.TargetSite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateByDomain", ctx, arg1, name, baseURL)
	ret0, _ := ret[0].(domain.TargetSite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateByDomain indicates an expected call of GetOrCreateByDomain.
func (mr *MockTargetSiteRepositoryMockRecorder) GetOrCreateByDomain(ctx, arg1, name, baseURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateByDomain", reflect.TypeOf((*MockTargetSiteRepository)(nil).GetOrCreateByDomain), ctx, arg1, name, baseURL)
}

// List mocks base method.
func (m *MockTargetSiteRepository) List(ctx context.Context) ([]domain.TargetSite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.TargetSite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTargetSiteRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTargetSiteRepository)(nil).List), ctx)
}

// MockOriginalSessionRepository is a mock of OriginalSessionRepository interface.
type MockOriginalSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOriginalSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockOriginalSessionRepositoryMockRecorder is the mock recorder for MockOriginalSessionRepository.
type MockOriginalSessionRepositoryMockRecorder struct {
	mock *MockOriginalSessionRepository
}

// NewMockOriginalSessionRepository creates a new mock instance.
func NewMockOriginalSessionRepository(ctrl *gomock.Controller) *MockOriginalSessionRepository {
	mock := &MockOriginalSessionRepository{ctrl: ctrl}
	mock.recorder = &MockOriginalSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOriginalSessionRepository) EXPECT() *MockOriginalSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOriginalSessionRepository) Create(ctx context.Context, s domain.OriginalSession) (domain.OriginalSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(domain.OriginalSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOriginalSessionRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOriginalSessionRepository)(nil).Create), ctx, s)
}

// GetByID mocks base method.
func (m *MockOriginalSessionRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.OriginalSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.OriginalSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOriginalSessionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOriginalSessionRepository)(nil).GetByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockOriginalSessionRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]domain.OriginalSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.OriginalSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockOriginalSessionRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockOriginalSessionRepository)(nil).ListByUser), ctx, userID)
}

// UpdateStatus mocks base method.
func (m *MockOriginalSessionRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockOriginalSessionRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockOriginalSessionRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockSessionCookieRepository is a mock of SessionCookieRepository interface.
type MockSessionCookieRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCookieRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionCookieRepositoryMockRecorder is the mock recorder for MockSessionCookieRepository.
type MockSessionCookieRepositoryMockRecorder struct {
	mock *MockSessionCookieRepository
}

// NewMockSessionCookieRepository creates a new mock instance.
func NewMockSessionCookieRepository(ctrl *gomock.Controller) *MockSessionCookieRepository {
	mock := &MockSessionCookieRepository{ctrl: ctrl}
	mock.recorder = &MockSessionCookieRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCookieRepository) EXPECT() *MockSessionCookieRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockSessionCookieRepository) CreateBatch(ctx context.Context, cookies []domain.SessionCookie) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, cookies)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockSessionCookieRepositoryMockRecorder) CreateBatch(ctx, cookies any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockSessionCookieRepository)(nil).CreateBatch), ctx, cookies)
}

// ListBySession mocks base method.
func (m *MockSessionCookieRepository) ListBySession(ctx context.Context, originalSessionID uuid.UUID) ([]domain.SessionCookie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySession", ctx, originalSessionID)
	ret0, _ := ret[0].([]domain.SessionCookie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySession indicates an expected call of ListBySession.
func (mr *MockSessionCookieRepositoryMockRecorder) ListBySession(ctx, originalSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySession", reflect.TypeOf((*MockSessionCookieRepository)(nil).ListBySession), ctx, originalSessionID)
}

// MockSessionTokenRepository is a mock of SessionTokenRepository interface.
type MockSessionTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionTokenRepositoryMockRecorder is the mock recorder for MockSessionTokenRepository.
type MockSessionTokenRepositoryMockRecorder struct {
	mock *MockSessionTokenRepository
}

// NewMockSessionTokenRepository creates a new mock instance.
func NewMockSessionTokenRepository(ctrl *gomock.Controller) *MockSessionTokenRepository {
	mock := &MockSessionTokenRepository{ctrl: ctrl}
	mock.recorder = &MockSessionTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionTokenRepository) EXPECT() *MockSessionTokenRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockSessionTokenRepository) CreateBatch(ctx context.Context, tokens []domain.SessionToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, tokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockSessionTokenRepositoryMockRecorder) CreateBatch(ctx, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockSessionTokenRepository)(nil).CreateBatch), ctx, tokens)
}

// ListBySession mocks base method.
func (m *MockSessionTokenRepository) ListBySession(ctx context.Context, originalSessionID uuid.UUID) ([]domain.SessionToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySession", ctx, originalSessionID)
	ret0, _ := ret[0].([]domain.SessionToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySession indicates an expected call of ListBySession.
func (mr *MockSessionTokenRepositoryMockRecorder) ListBySession(ctx, originalSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySession", reflect.TypeOf((*MockSessionTokenRepository)(nil).ListBySession), ctx, originalSessionID)
}

// MockSharedLinkRepository is a mock of SharedLinkRepository interface.
type MockSharedLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSharedLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockSharedLinkRepositoryMockRecorder is the mock recorder for MockSharedLinkRepository.
type MockSharedLinkRepositoryMockRecorder struct {
	mock *MockSharedLinkRepository
}

// NewMockSharedLinkRepository creates a new mock instance.
func NewMockSharedLinkRepository(ctrl *gomock.Controller) *MockSharedLinkRepository {
	mock := &MockSharedLinkRepository{ctrl: ctrl}
	mock.recorder = &MockSharedLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSharedLinkRepository) EXPECT() *MockSharedLinkRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSharedLinkRepository) Create(ctx context.Context, l domain.SharedLink) (domain.SharedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, l)
	ret0, _ := ret[0].(domain.SharedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSharedLinkRepositoryMockRecorder) Create(ctx, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSharedLinkRepository)(nil).Create), ctx, l)
}

// GetByID mocks base method.
func (m *MockSharedLinkRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.SharedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.SharedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSharedLinkRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSharedLinkRepository)(nil).GetByID), ctx, id)
}

// GetByToken mocks base method.
func (m *MockSharedLinkRepository) GetByToken(ctx context.Context, token string) (domain.LinkWithSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(domain.LinkWithSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockSharedLinkRepositoryMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockSharedLinkRepository)(nil).GetByToken), ctx, token)
}

// ListByUser mocks base method.
func (m *MockSharedLinkRepository) ListByUser(ctx context.Context, userID uuid.UUID, status string) ([]domain.SharedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, status)
	ret0, _ := ret[0].([]domain.SharedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockSharedLinkRepositoryMockRecorder) ListByUser(ctx, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockSharedLinkRepository)(nil).ListByUser), ctx, userID, status)
}

// OwnerUserID mocks base method.
func (m *MockSharedLinkRepository) OwnerUserID(ctx context.Context, linkID uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnerUserID", ctx, linkID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OwnerUserID indicates an expected call of OwnerUserID.
func (mr *MockSharedLinkRepositoryMockRecorder) OwnerUserID(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnerUserID", reflect.TypeOf((*MockSharedLinkRepository)(nil).OwnerUserID), ctx, linkID)
}

// UpdateStatus mocks base method.
func (m *MockSharedLinkRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockSharedLinkRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockSharedLinkRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockAccessPolicyRepository is a mock of AccessPolicyRepository interface.
type MockAccessPolicyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccessPolicyRepositoryMockRecorder
	isgomock struct{}
}

// MockAccessPolicyRepositoryMockRecorder is the mock recorder for MockAccessPolicyRepository.
type MockAccessPolicyRepositoryMockRecorder struct {
	mock *MockAccessPolicyRepository
}

// NewMockAccessPolicyRepository creates a new mock instance.
func NewMockAccessPolicyRepository(ctrl *gomock.Controller) *MockAccessPolicyRepository {
	mock := &MockAccessPolicyRepository{ctrl: ctrl}
	mock.recorder = &MockAccessPolicyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessPolicyRepository) EXPECT() *MockAccessPolicyRepositoryMockRecorder {
	return m.recorder
}

// AttachToLink mocks base method.
func (m *MockAccessPolicyRepository) AttachToLink(ctx context.Context, linkID, policyID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachToLink", ctx, linkID, policyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachToLink indicates an expected call of AttachToLink.
func (mr *MockAccessPolicyRepositoryMockRecorder) AttachToLink(ctx, linkID, policyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachToLink", reflect.TypeOf((*MockAccessPolicyRepository)(nil).AttachToLink), ctx, linkID, policyID)
}

// Create mocks base method.
func (m *MockAccessPolicyRepository) Create(ctx context.Context, p domain.AccessPolicy) (domain.AccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(domain.AccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccessPolicyRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccessPolicyRepository)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockAccessPolicyRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAccessPolicyRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccessPolicyRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAccessPolicyRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.AccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.AccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccessPolicyRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccessPolicyRepository)(nil).GetByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockAccessPolicyRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]domain.AccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.AccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockAccessPolicyRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockAccessPolicyRepository)(nil).ListByUser), ctx, userID)
}

// ListForLink mocks base method.
func (m *MockAccessPolicyRepository) ListForLink(ctx context.Context, linkID uuid.UUID) ([]domain.AccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForLink", ctx, linkID)
	ret0, _ := ret[0].([]domain.AccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForLink indicates an expected call of ListForLink.
func (mr *MockAccessPolicyRepositoryMockRecorder) ListForLink(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForLink", reflect.TypeOf((*MockAccessPolicyRepository)(nil).ListForLink), ctx, linkID)
}

// MockBlacklistRepository is a mock of BlacklistRepository interface.
type MockBlacklistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlacklistRepositoryMockRecorder
	isgomock struct{}
}

// MockBlacklistRepositoryMockRecorder is the mock recorder for MockBlacklistRepository.
type MockBlacklistRepositoryMockRecorder struct {
	mock *MockBlacklistRepository
}

// NewMockBlacklistRepository creates a new mock instance.
func NewMockBlacklistRepository(ctrl *gomock.Controller) *MockBlacklistRepository {
	mock := &MockBlacklistRepository{ctrl: ctrl}
	mock.recorder = &MockBlacklistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlacklistRepository) EXPECT() *MockBlacklistRepositoryMockRecorder {
	return m.recorder
}

// AttachToLink mocks base method.
func (m *MockBlacklistRepository) AttachToLink(ctx context.Context, linkID, endpointID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachToLink", ctx, linkID, endpointID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachToLink indicates an expected call of AttachToLink.
func (mr *MockBlacklistRepositoryMockRecorder) AttachToLink(ctx, linkID, endpointID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachToLink", reflect.TypeOf((*MockBlacklistRepository)(nil).AttachToLink), ctx, linkID, endpointID)
}

// AttachToSite mocks base method.
func (m *MockBlacklistRepository) AttachToSite(ctx context.Context, siteID, endpointID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachToSite", ctx, siteID, endpointID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachToSite indicates an expected call of AttachToSite.
func (mr *MockBlacklistRepositoryMockRecorder) AttachToSite(ctx, siteID, endpointID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachToSite", reflect.TypeOf((*MockBlacklistRepository)(nil).AttachToSite), ctx, siteID, endpointID)
}

// Create mocks base method.
func (m *MockBlacklistRepository) Create(ctx context.Context, e domain.BlacklistedEndpoint) (domain.BlacklistedEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(domain.BlacklistedEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBlacklistRepositoryMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlacklistRepository)(nil).Create), ctx, e)
}

// Delete mocks base method.
func (m *MockBlacklistRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlacklistRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlacklistRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockBlacklistRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.BlacklistedEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.BlacklistedEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBlacklistRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBlacklistRepository)(nil).GetByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockBlacklistRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]domain.BlacklistedEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.BlacklistedEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockBlacklistRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockBlacklistRepository)(nil).ListByUser), ctx, userID)
}

// RulesForLink mocks base method.
func (m *MockBlacklistRepository) RulesForLink(ctx context.Context, linkID, targetSiteID uuid.UUID) ([]domain.BlacklistedEndpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RulesForLink", ctx, linkID, targetSiteID)
	ret0, _ := ret[0].([]domain.BlacklistedEndpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RulesForLink indicates an expected call of RulesForLink.
func (mr *MockBlacklistRepositoryMockRecorder) RulesForLink(ctx, linkID, targetSiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RulesForLink", reflect.TypeOf((*MockBlacklistRepository)(nil).RulesForLink), ctx, linkID, targetSiteID)
}

// SetBlockedMethods mocks base method.
func (m *MockBlacklistRepository) SetBlockedMethods(ctx context.Context, endpointID uuid.UUID, methods []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBlockedMethods", ctx, endpointID, methods)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBlockedMethods indicates an expected call of SetBlockedMethods.
func (mr *MockBlacklistRepositoryMockRecorder) SetBlockedMethods(ctx, endpointID, methods any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlockedMethods", reflect.TypeOf((*MockBlacklistRepository)(nil).SetBlockedMethods), ctx, endpointID, methods)
}

// MockGuestRepository is a mock of GuestRepository interface.
type MockGuestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGuestRepositoryMockRecorder
	isgomock struct{}
}

// MockGuestRepositoryMockRecorder is the mock recorder for MockGuestRepository.
type MockGuestRepositoryMockRecorder struct {
	mock *MockGuestRepository
}

// NewMockGuestRepository creates a new mock instance.
func NewMockGuestRepository(ctrl *gomock.Controller) *MockGuestRepository {
	mock := &MockGuestRepository{ctrl: ctrl}
	mock.recorder = &MockGuestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuestRepository) EXPECT() *MockGuestRepositoryMockRecorder {
	return m.recorder
}

// GetOrCreate mocks base method.
func (m *MockGuestRepository) GetOrCreate(ctx context.Context, ipAddress, userAgent, fingerprint string) (domain.Guest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", ctx, ipAddress, userAgent, fingerprint)
	ret0, _ := ret[0].(domain.Guest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockGuestRepositoryMockRecorder) GetOrCreate(ctx, ipAddress, userAgent, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockGuestRepository)(nil).GetOrCreate), ctx, ipAddress, userAgent, fingerprint)
}

// List mocks base method.
func (m *MockGuestRepository) List(ctx context.Context, limit, offset int) ([]domain.Guest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]domain.Guest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGuestRepositoryMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGuestRepository)(nil).List), ctx, limit, offset)
}

// MockGuestSessionRepository is a mock of GuestSessionRepository interface.
type MockGuestSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGuestSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockGuestSessionRepositoryMockRecorder is the mock recorder for MockGuestSessionRepository.
type MockGuestSessionRepositoryMockRecorder struct {
	mock *MockGuestSessionRepository
}

// NewMockGuestSessionRepository creates a new mock instance.
func NewMockGuestSessionRepository(ctrl *gomock.Controller) *MockGuestSessionRepository {
	mock := &MockGuestSessionRepository{ctrl: ctrl}
	mock.recorder = &MockGuestSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuestSessionRepository) EXPECT() *MockGuestSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGuestSessionRepository) Create(ctx context.Context, gs domain.GuestSession) (domain.GuestSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, gs)
	ret0, _ := ret[0].(domain.GuestSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGuestSessionRepositoryMockRecorder) Create(ctx, gs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGuestSessionRepository)(nil).Create), ctx, gs)
}

// GetActiveByLinkAndGuest mocks base method.
func (m *MockGuestSessionRepository) GetActiveByLinkAndGuest(ctx context.Context, linkID uuid.UUID, guestID *uuid.UUID) (*domain.GuestSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByLinkAndGuest", ctx, linkID, guestID)
	ret0, _ := ret[0].(*domain.GuestSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByLinkAndGuest indicates an expected call of GetActiveByLinkAndGuest.
func (mr *MockGuestSessionRepositoryMockRecorder) GetActiveByLinkAndGuest(ctx, linkID, guestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByLinkAndGuest", reflect.TypeOf((*MockGuestSessionRepository)(nil).GetActiveByLinkAndGuest), ctx, linkID, guestID)
}

// ListByLink mocks base method.
func (m *MockGuestSessionRepository) ListByLink(ctx context.Context, linkID uuid.UUID) ([]domain.GuestSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByLink", ctx, linkID)
	ret0, _ := ret[0].([]domain.GuestSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByLink indicates an expected call of ListByLink.
func (mr *MockGuestSessionRepositoryMockRecorder) ListByLink(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByLink", reflect.TypeOf((*MockGuestSessionRepository)(nil).ListByLink), ctx, linkID)
}

// Terminate mocks base method.
func (m *MockGuestSessionRepository) Terminate(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Terminate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Terminate indicates an expected call of Terminate.
func (mr *MockGuestSessionRepositoryMockRecorder) Terminate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockGuestSessionRepository)(nil).Terminate), ctx, id)
}

// TouchLastRequest mocks base method.
func (m *MockGuestSessionRepository) TouchLastRequest(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLastRequest", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLastRequest indicates an expected call of TouchLastRequest.
func (mr *MockGuestSessionRepositoryMockRecorder) TouchLastRequest(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLastRequest", reflect.TypeOf((*MockGuestSessionRepository)(nil).TouchLastRequest), ctx, id)
}

// MockUsageCounterRepository is a mock of UsageCounterRepository interface.
type MockUsageCounterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUsageCounterRepositoryMockRecorder
	isgomock struct{}
}

// MockUsageCounterRepositoryMockRecorder is the mock recorder for MockUsageCounterRepository.
type MockUsageCounterRepositoryMockRecorder struct {
	mock *MockUsageCounterRepository
}

// NewMockUsageCounterRepository creates a new mock instance.
func NewMockUsageCounterRepository(ctrl *gomock.Controller) *MockUsageCounterRepository {
	mock := &MockUsageCounterRepository{ctrl: ctrl}
	mock.recorder = &MockUsageCounterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageCounterRepository) EXPECT() *MockUsageCounterRepositoryMockRecorder {
	return m.recorder
}

// GetByLink mocks base method.
func (m *MockUsageCounterRepository) GetByLink(ctx context.Context, linkID uuid.UUID) (domain.UsageCounters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLink", ctx, linkID)
	ret0, _ := ret[0].(domain.UsageCounters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLink indicates an expected call of GetByLink.
func (mr *MockUsageCounterRepositoryMockRecorder) GetByLink(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLink", reflect.TypeOf((*MockUsageCounterRepository)(nil).GetByLink), ctx, linkID)
}

// Upsert mocks base method.
func (m *MockUsageCounterRepository) Upsert(ctx context.Context, c domain.UsageCounters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockUsageCounterRepositoryMockRecorder) Upsert(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockUsageCounterRepository)(nil).Upsert), ctx, c)
}

// MockProxyAccessLogRepository is a mock of ProxyAccessLogRepository interface.
type MockProxyAccessLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProxyAccessLogRepositoryMockRecorder
	isgomock struct{}
}

// MockProxyAccessLogRepositoryMockRecorder is the mock recorder for MockProxyAccessLogRepository.
type MockProxyAccessLogRepositoryMockRecorder struct {
	mock *MockProxyAccessLogRepository
}

// NewMockProxyAccessLogRepository creates a new mock instance.
func NewMockProxyAccessLogRepository(ctrl *gomock.Controller) *MockProxyAccessLogRepository {
	mock := &MockProxyAccessLogRepository{ctrl: ctrl}
	mock.recorder = &MockProxyAccessLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyAccessLogRepository) EXPECT() *MockProxyAccessLogRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockProxyAccessLogRepository) Insert(ctx context.Context, l domain.ProxyAccessLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockProxyAccessLogRepositoryMockRecorder) Insert(ctx, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockProxyAccessLogRepository)(nil).Insert), ctx, l)
}

// InsertBatch mocks base method.
func (m *MockProxyAccessLogRepository) InsertBatch(ctx context.Context, logs []domain.ProxyAccessLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBatch", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBatch indicates an expected call of InsertBatch.
func (mr *MockProxyAccessLogRepositoryMockRecorder) InsertBatch(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBatch", reflect.TypeOf((*MockProxyAccessLogRepository)(nil).InsertBatch), ctx, logs)
}

// ListByLink mocks base method.
func (m *MockProxyAccessLogRepository) ListByLink(ctx context.Context, linkID uuid.UUID, limit int) ([]domain.ProxyAccessLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByLink", ctx, linkID, limit)
	ret0, _ := ret[0].([]domain.ProxyAccessLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByLink indicates an expected call of ListByLink.
func (mr *MockProxyAccessLogRepositoryMockRecorder) ListByLink(ctx, linkID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByLink", reflect.TypeOf((*MockProxyAccessLogRepository)(nil).ListByLink), ctx, linkID, limit)
}

// MockLinkTerminationRepository is a mock of LinkTerminationRepository interface.
type MockLinkTerminationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkTerminationRepositoryMockRecorder
	isgomock struct{}
}

// MockLinkTerminationRepositoryMockRecorder is the mock recorder for MockLinkTerminationRepository.
type MockLinkTerminationRepositoryMockRecorder struct {
	mock *MockLinkTerminationRepository
}

// NewMockLinkTerminationRepository creates a new mock instance.
func NewMockLinkTerminationRepository(ctrl *gomock.Controller) *MockLinkTerminationRepository {
	mock := &MockLinkTerminationRepository{ctrl: ctrl}
	mock.recorder = &MockLinkTerminationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkTerminationRepository) EXPECT() *MockLinkTerminationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLinkTerminationRepository) Create(ctx context.Context, t domain.LinkTermination) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLinkTerminationRepositoryMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLinkTerminationRepository)(nil).Create), ctx, t)
}

// GetByLink mocks base method.
func (m *MockLinkTerminationRepository) GetByLink(ctx context.Context, linkID uuid.UUID) (*domain.LinkTermination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLink", ctx, linkID)
	ret0, _ := ret[0].(*domain.LinkTermination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLink indicates an expected call of GetByLink.
func (mr *MockLinkTerminationRepositoryMockRecorder) GetByLink(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLink", reflect.TypeOf((*MockLinkTerminationRepository)(nil).GetByLink), ctx, linkID)
}

// ListReasons mocks base method.
func (m *MockLinkTerminationRepository) ListReasons(ctx context.Context) ([]domain.RevocationReason, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReasons", ctx)
	ret0, _ := ret[0].([]domain.RevocationReason)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReasons indicates an expected call of ListReasons.
func (mr *MockLinkTerminationRepositoryMockRecorder) ListReasons(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReasons", reflect.TypeOf((*MockLinkTerminationRepository)(nil).ListReasons), ctx)
}

// MockSecurityEventRepository is a mock of SecurityEventRepository interface.
type MockSecurityEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityEventRepositoryMockRecorder
	isgomock struct{}
}

// MockSecurityEventRepositoryMockRecorder is the mock recorder for MockSecurityEventRepository.
type MockSecurityEventRepositoryMockRecorder struct {
	mock *MockSecurityEventRepository
}

// NewMockSecurityEventRepository creates a new mock instance.
func NewMockSecurityEventRepository(ctrl *gomock.Controller) *MockSecurityEventRepository {
	mock := &MockSecurityEventRepository{ctrl: ctrl}
	mock.recorder = &MockSecurityEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityEventRepository) EXPECT() *MockSecurityEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSecurityEventRepository) Create(ctx context.Context, e domain.SecurityEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSecurityEventRepositoryMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSecurityEventRepository)(nil).Create), ctx, e)
}

// ListByLink mocks base method.
func (m *MockSecurityEventRepository) ListByLink(ctx context.Context, linkID uuid.UUID, limit int) ([]domain.SecurityEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByLink", ctx, linkID, limit)
	ret0, _ := ret[0].([]domain.SecurityEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByLink indicates an expected call of ListByLink.
func (mr *MockSecurityEventRepositoryMockRecorder) ListByLink(ctx, linkID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByLink", reflect.TypeOf((*MockSecurityEventRepository)(nil).ListByLink), ctx, linkID, limit)
}

// ListRecent mocks base method.
func (m *MockSecurityEventRepository) ListRecent(ctx context.Context, limit int) ([]domain.SecurityEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecent", ctx, limit)
	ret0, _ := ret[0].([]domain.SecurityEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecent indicates an expected call of ListRecent.
func (mr *MockSecurityEventRepositoryMockRecorder) ListRecent(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecent", reflect.TypeOf((*MockSecurityEventRepository)(nil).ListRecent), ctx, limit)
}

// MockStatsRepository is a mock of StatsRepository interface.
type MockStatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatsRepositoryMockRecorder
	isgomock struct{}
}

// MockStatsRepositoryMockRecorder is the mock recorder for MockStatsRepository.
type MockStatsRepositoryMockRecorder struct {
	mock *MockStatsRepository
}

// NewMockStatsRepository creates a new mock instance.
func NewMockStatsRepository(ctrl *gomock.Controller) *MockStatsRepository {
	mock := &MockStatsRepository{ctrl: ctrl}
	mock.recorder = &MockStatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsRepository) EXPECT() *MockStatsRepositoryMockRecorder {
	return m.recorder
}

// GetLinkStats mocks base method.
func (m *MockStatsRepository) GetLinkStats(ctx context.Context, linkID uuid.UUID) (*domain.LinkStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkStats", ctx, linkID)
	ret0, _ := ret[0].(*domain.LinkStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkStats indicates an expected call of GetLinkStats.
func (mr *MockStatsRepositoryMockRecorder) GetLinkStats(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkStats", reflect.TypeOf((*MockStatsRepository)(nil).GetLinkStats), ctx, linkID)
}

// RefreshMaterializedView mocks base method.
func (m *MockStatsRepository) RefreshMaterializedView(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshMaterializedView", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshMaterializedView indicates an expected call of RefreshMaterializedView.
func (mr *MockStatsRepositoryMockRecorder) RefreshMaterializedView(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshMaterializedView", reflect.TypeOf((*MockStatsRepository)(nil).RefreshMaterializedView), ctx)
}
