// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: sessionproxy/v1/admin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_StreamLinkActivity_FullMethodName = "/sessionproxy.v1.AdminService/StreamLinkActivity"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService streams link activity (auto-terminations and blacklist
// violations) in real time. It exists alongside the REST/SSE dashboard
// feed (internal/transport/webui) as a typed, protocol-level alternative
// for external consumers - a CLI monitor, or a future companion app -
// that REST polling does not serve efficiently. It is read-only: nothing
// here is a substitute for the REST control plane, which remains the
// only way to create/modify resources.
type AdminServiceClient interface {
	// StreamLinkActivity streams events as they happen. An empty link_id in
	// the request means "stream every link the caller can see" - callers
	// authenticate the same way as the REST API (owner JWT or API key), and
	// the server only ever streams events for shared_links owned by the
	// authenticated user.
	StreamLinkActivity(ctx context.Context, in *StreamLinkActivityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LinkActivityEvent], error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) StreamLinkActivity(ctx context.Context, in *StreamLinkActivityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LinkActivityEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[0], AdminService_StreamLinkActivity_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLinkActivityRequest, LinkActivityEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_StreamLinkActivityClient = grpc.ServerStreamingClient[LinkActivityEvent]

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService streams link activity (auto-terminations and blacklist
// violations) in real time. It exists alongside the REST/SSE dashboard
// feed (internal/transport/webui) as a typed, protocol-level alternative
// for external consumers - a CLI monitor, or a future companion app -
// that REST polling does not serve efficiently. It is read-only: nothing
// here is a substitute for the REST control plane, which remains the
// only way to create/modify resources.
type AdminServiceServer interface {
	// StreamLinkActivity streams events as they happen. An empty link_id in
	// the request means "stream every link the caller can see" - callers
	// authenticate the same way as the REST API (owner JWT or API key), and
	// the server only ever streams events for shared_links owned by the
	// authenticated user.
	StreamLinkActivity(*StreamLinkActivityRequest, grpc.ServerStreamingServer[LinkActivityEvent]) error
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) StreamLinkActivity(*StreamLinkActivityRequest, grpc.ServerStreamingServer[LinkActivityEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamLinkActivity not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_StreamLinkActivity_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLinkActivityRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).StreamLinkActivity(m, &grpc.GenericServerStream[StreamLinkActivityRequest, LinkActivityEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_StreamLinkActivityServer = grpc.ServerStreamingServer[LinkActivityEvent]

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sessionproxy.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLinkActivity",
			Handler:       _AdminService_StreamLinkActivity_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sessionproxy/v1/admin.proto",
}
