// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sessionproxy/v1/admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkActivityEventType int32

const (
	LinkActivityEventType_LINK_ACTIVITY_EVENT_TYPE_UNSPECIFIED         LinkActivityEventType = 0
	LinkActivityEventType_LINK_ACTIVITY_EVENT_TYPE_BLACKLIST_VIOLATION LinkActivityEventType = 1
	LinkActivityEventType_LINK_ACTIVITY_EVENT_TYPE_LINK_TERMINATED     LinkActivityEventType = 2
)

// Enum value maps for LinkActivityEventType.
var (
	LinkActivityEventType_name = map[int32]string{
		0: "LINK_ACTIVITY_EVENT_TYPE_UNSPECIFIED",
		1: "LINK_ACTIVITY_EVENT_TYPE_BLACKLIST_VIOLATION",
		2: "LINK_ACTIVITY_EVENT_TYPE_LINK_TERMINATED",
	}
	LinkActivityEventType_value = map[string]int32{
		"LINK_ACTIVITY_EVENT_TYPE_UNSPECIFIED":         0,
		"LINK_ACTIVITY_EVENT_TYPE_BLACKLIST_VIOLATION": 1,
		"LINK_ACTIVITY_EVENT_TYPE_LINK_TERMINATED":     2,
	}
)

func (x LinkActivityEventType) Enum() *LinkActivityEventType {
	p := new(LinkActivityEventType)
	*p = x
	return p
}

func (x LinkActivityEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkActivityEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_sessionproxy_v1_admin_proto_enumTypes[0].Descriptor()
}

func (LinkActivityEventType) Type() protoreflect.EnumType {
	return &file_sessionproxy_v1_admin_proto_enumTypes[0]
}

func (x LinkActivityEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkActivityEventType.Descriptor instead.
func (LinkActivityEventType) EnumDescriptor() ([]byte, []int) {
	return file_sessionproxy_v1_admin_proto_rawDescGZIP(), []int{0}
}

type StreamLinkActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"` // optional; empty = all of the caller's links
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLinkActivityRequest) Reset() {
	*x = StreamLinkActivityRequest{}
	mi := &file_sessionproxy_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLinkActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLinkActivityRequest) ProtoMessage() {}

func (x *StreamLinkActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionproxy_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLinkActivityRequest.ProtoReflect.Descriptor instead.
func (*StreamLinkActivityRequest) Descriptor() ([]byte, []int) {
	return file_sessionproxy_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *StreamLinkActivityRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

type LinkActivityEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LinkActivityEventType  `protobuf:"varint,1,opt,name=type,proto3,enum=sessionproxy.v1.LinkActivityEventType" json:"type,omitempty"`
	LinkId        string                 `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkActivityEvent) Reset() {
	*x = LinkActivityEvent{}
	mi := &file_sessionproxy_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkActivityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkActivityEvent) ProtoMessage() {}

func (x *LinkActivityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sessionproxy_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkActivityEvent.ProtoReflect.Descriptor instead.
func (*LinkActivityEvent) Descriptor() ([]byte, []int) {
	return file_sessionproxy_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *LinkActivityEvent) GetType() LinkActivityEventType {
	if x != nil {
		return x.Type
	}
	return LinkActivityEventType_LINK_ACTIVITY_EVENT_TYPE_UNSPECIFIED
}

func (x *LinkActivityEvent) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *LinkActivityEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LinkActivityEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_sessionproxy_v1_admin_proto protoreflect.FileDescriptor

const file_sessionproxy_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1bsessionproxy/v1/admin.proto\x12\x0fsessionproxy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\x19StreamLinkActivityRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\"\xbf\x01\n" +
	"\x11LinkActivityEvent\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.sessionproxy.v1.LinkActivityEventTypeR\x04type\x12\x17\n" +
	"\alink_id\x18\x02 \x01(\tR\x06linkId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt*\xa1\x01\n" +
	"\x15LinkActivityEventType\x12(\n" +
	"$LINK_ACTIVITY_EVENT_TYPE_UNSPECIFIED\x10\x00\x120\n" +
	",LINK_ACTIVITY_EVENT_TYPE_BLACKLIST_VIOLATION\x10\x01\x12,\n" +
	"(LINK_ACTIVITY_EVENT_TYPE_LINK_TERMINATED\x10\x022v\n" +
	"\fAdminService\x12f\n" +
	"\x12StreamLinkActivity\x12*.sessionproxy.v1.StreamLinkActivityRequest\x1a\".sessionproxy.v1.LinkActivityEvent0\x01B,Z*sessionproxy/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_sessionproxy_v1_admin_proto_rawDescOnce sync.Once
	file_sessionproxy_v1_admin_proto_rawDescData []byte
)

func file_sessionproxy_v1_admin_proto_rawDescGZIP() []byte {
	file_sessionproxy_v1_admin_proto_rawDescOnce.Do(func() {
		file_sessionproxy_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessionproxy_v1_admin_proto_rawDesc), len(file_sessionproxy_v1_admin_proto_rawDesc)))
	})
	return file_sessionproxy_v1_admin_proto_rawDescData
}

var file_sessionproxy_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sessionproxy_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sessionproxy_v1_admin_proto_goTypes = []any{
	(LinkActivityEventType)(0),        // 0: sessionproxy.v1.LinkActivityEventType
	(*StreamLinkActivityRequest)(nil), // 1: sessionproxy.v1.StreamLinkActivityRequest
	(*LinkActivityEvent)(nil),         // 2: sessionproxy.v1.LinkActivityEvent
	(*timestamppb.Timestamp)(nil),     // 3: google.protobuf.Timestamp
}
var file_sessionproxy_v1_admin_proto_depIdxs = []int32{
	0, // 0: sessionproxy.v1.LinkActivityEvent.type:type_name -> sessionproxy.v1.LinkActivityEventType
	3, // 1: sessionproxy.v1.LinkActivityEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 2: sessionproxy.v1.AdminService.StreamLinkActivity:input_type -> sessionproxy.v1.StreamLinkActivityRequest
	2, // 3: sessionproxy.v1.AdminService.StreamLinkActivity:output_type -> sessionproxy.v1.LinkActivityEvent
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sessionproxy_v1_admin_proto_init() }
func file_sessionproxy_v1_admin_proto_init() {
	if File_sessionproxy_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessionproxy_v1_admin_proto_rawDesc), len(file_sessionproxy_v1_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sessionproxy_v1_admin_proto_goTypes,
		DependencyIndexes: file_sessionproxy_v1_admin_proto_depIdxs,
		EnumInfos:         file_sessionproxy_v1_admin_proto_enumTypes,
		MessageInfos:      file_sessionproxy_v1_admin_proto_msgTypes,
	}.Build()
	File_sessionproxy_v1_admin_proto = out.File
	file_sessionproxy_v1_admin_proto_goTypes = nil
	file_sessionproxy_v1_admin_proto_depIdxs = nil
}
