// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: sessionproxy/v1/import.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImportService_ImportSession_FullMethodName = "/sessionproxy.v1.ImportService/ImportSession"
)

// ImportServiceClient is the client API for ImportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ImportService is the gRPC counterpart to POST /api/v1/sessions/import,
// meant for the kind of client the api_keys table exists for per
// README.md group 1 ("ключи доступа для браузерных расширений/CLI"): a
// CLI tool or browser extension that already has a typed client
// generated from this .proto, rather than a REST client hand-rolled
// against api/openapi.yaml. It is not a 1:1 mirror of the REST surface -
// only the one operation that this class of client actually needs.
//
// Authentication is an API key (api_keys.key_hash), sent as gRPC metadata
// "authorization: Bearer spk_...", not a JWT - a CLI/extension is
// expected to hold a long-lived key, not go through interactive login.
type ImportServiceClient interface {
	ImportSession(ctx context.Context, in *ImportSessionRequest, opts ...grpc.CallOption) (*ImportSessionResponse, error)
}

type importServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImportServiceClient(cc grpc.ClientConnInterface) ImportServiceClient {
	return &importServiceClient{cc}
}

func (c *importServiceClient) ImportSession(ctx context.Context, in *ImportSessionRequest, opts ...grpc.CallOption) (*ImportSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportSessionResponse)
	err := c.cc.Invoke(ctx, ImportService_ImportSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImportServiceServer is the server API for ImportService service.
// All implementations must embed UnimplementedImportServiceServer
// for forward compatibility.
//
// ImportService is the gRPC counterpart to POST /api/v1/sessions/import,
// meant for the kind of client the api_keys table exists for per
// README.md group 1 ("ключи доступа для браузерных расширений/CLI"): a
// CLI tool or browser extension that already has a typed client
// generated from this .proto, rather than a REST client hand-rolled
// against api/openapi.yaml. It is not a 1:1 mirror of the REST surface -
// only the one operation that this class of client actually needs.
//
// Authentication is an API key (api_keys.key_hash), sent as gRPC metadata
// "authorization: Bearer spk_...", not a JWT - a CLI/extension is
// expected to hold a long-lived key, not go through interactive login.
type ImportServiceServer interface {
	ImportSession(context.Context, *ImportSessionRequest) (*ImportSessionResponse, error)
	mustEmbedUnimplementedImportServiceServer()
}

// UnimplementedImportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImportServiceServer struct{}

func (UnimplementedImportServiceServer) ImportSession(context.Context, *ImportSessionRequest) (*ImportSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportSession not implemented")
}
func (UnimplementedImportServiceServer) mustEmbedUnimplementedImportServiceServer() {}
func (UnimplementedImportServiceServer) testEmbeddedByValue()                       {}

// UnsafeImportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImportServiceServer will
// result in compilation errors.
type UnsafeImportServiceServer interface {
	mustEmbedUnimplementedImportServiceServer()
}

func RegisterImportServiceServer(s grpc.ServiceRegistrar, srv ImportServiceServer) {
	// If the following call panics, it indicates UnimplementedImportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImportService_ServiceDesc, srv)
}

func _ImportService_ImportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ImportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ImportSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ImportSession(ctx, req.(*ImportSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImportService_ServiceDesc is the grpc.ServiceDesc for ImportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sessionproxy.v1.ImportService",
	HandlerType: (*ImportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImportSession",
			Handler:    _ImportService_ImportSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sessionproxy/v1/import.proto",
}
