// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sessionproxy/v1/import.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CookieInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // plaintext; encrypted server-side before storage
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Secure        bool                   `protobuf:"varint,5,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly      bool                   `protobuf:"varint,6,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	SameSite      string                 `protobuf:"bytes,7,opt,name=same_site,json=sameSite,proto3" json:"same_site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CookieInput) Reset() {
	*x = CookieInput{}
	mi := &file_sessionproxy_v1_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CookieInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookieInput) ProtoMessage() {}

func (x *CookieInput) ProtoReflect() protoreflect.Message {
	mi := &file_sessionproxy_v1_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookieInput.ProtoReflect.Descriptor instead.
func (*CookieInput) Descriptor() ([]byte, []int) {
	return file_sessionproxy_v1_import_proto_rawDescGZIP(), []int{0}
}

func (x *CookieInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CookieInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CookieInput) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CookieInput) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CookieInput) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *CookieInput) GetHttpOnly() bool {
	if x != nil {
		return x.HttpOnly
	}
	return false
}

func (x *CookieInput) GetSameSite() string {
	if x != nil {
		return x.SameSite
	}
	return ""
}

type TokenInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenType     string                 `protobuf:"bytes,1,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	HeaderName    string                 `protobuf:"bytes,2,opt,name=header_name,json=headerName,proto3" json:"header_name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // plaintext; encrypted server-side before storage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInput) Reset() {
	*x = TokenInput{}
	mi := &file_sessionproxy_v1_import_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInput) ProtoMessage() {}

func (x *TokenInput) ProtoReflect() protoreflect.Message {
	mi := &file_sessionproxy_v1_import_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInput.ProtoReflect.Descriptor instead.
func (*TokenInput) Descriptor() ([]byte, []int) {
	return file_sessionproxy_v1_import_proto_rawDescGZIP(), []int{1}
}

func (x *TokenInput) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenInput) GetHeaderName() string {
	if x != nil {
		return x.HeaderName
	}
	return ""
}

func (x *TokenInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ImportSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseDomain    string                 `protobuf:"bytes,1,opt,name=base_domain,json=baseDomain,proto3" json:"base_domain,omitempty"`
	SiteName      string                 `protobuf:"bytes,2,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Cookies       []*CookieInput         `protobuf:"bytes,4,rep,name=cookies,proto3" json:"cookies,omitempty"`
	Tokens        []*TokenInput          `protobuf:"bytes,5,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSessionRequest) Reset() {
	*x = ImportSessionRequest{}
	mi := &file_sessionproxy_v1_import_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSessionRequest) ProtoMessage() {}

func (x *ImportSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionproxy_v1_import_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSessionRequest.ProtoReflect.Descriptor instead.
func (*ImportSessionRequest) Descriptor() ([]byte, []int) {
	return file_sessionproxy_v1_import_proto_rawDescGZIP(), []int{2}
}

func (x *ImportSessionRequest) GetBaseDomain() string {
	if x != nil {
		return x.BaseDomain
	}
	return ""
}

func (x *ImportSessionRequest) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *ImportSessionRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ImportSessionRequest) GetCookies() []*CookieInput {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *ImportSessionRequest) GetTokens() []*TokenInput {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type ImportSessionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalSessionId string                 `protobuf:"bytes,1,opt,name=original_session_id,json=originalSessionId,proto3" json:"original_session_id,omitempty"`
	TargetSiteId      string                 `protobuf:"bytes,2,opt,name=target_site_id,json=targetSiteId,proto3" json:"target_site_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ImportSessionResponse) Reset() {
	*x = ImportSessionResponse{}
	mi := &file_sessionproxy_v1_import_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSessionResponse) ProtoMessage() {}

func (x *ImportSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessionproxy_v1_import_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSessionResponse.ProtoReflect.Descriptor instead.
func (*ImportSessionResponse) Descriptor() ([]byte, []int) {
	return file_sessionproxy_v1_import_proto_rawDescGZIP(), []int{3}
}

func (x *ImportSessionResponse) GetOriginalSessionId() string {
	if x != nil {
		return x.OriginalSessionId
	}
	return ""
}

func (x *ImportSessionResponse) GetTargetSiteId() string {
	if x != nil {
		return x.TargetSiteId
	}
	return ""
}

var File_sessionproxy_v1_import_proto protoreflect.FileDescriptor

const file_sessionproxy_v1_import_proto_rawDesc = "" +
	"\n" +
	"\x1csessionproxy/v1/import.proto\x12\x0fsessionproxy.v1\"\xb5\x01\n" +
	"\vCookieInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06secure\x18\x05 \x01(\bR\x06secure\x12\x1b\n" +
	"\thttp_only\x18\x06 \x01(\bR\bhttpOnly\x12\x1b\n" +
	"\tsame_site\x18\a \x01(\tR\bsameSite\"b\n" +
	"\n" +
	"TokenInput\x12\x1d\n" +
	"\n" +
	"token_type\x18\x01 \x01(\tR\ttokenType\x12\x1f\n" +
	"\vheader_name\x18\x02 \x01(\tR\n" +
	"headerName\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xdc\x01\n" +
	"\x14ImportSessionRequest\x12\x1f\n" +
	"\vbase_domain\x18\x01 \x01(\tR\n" +
	"baseDomain\x12\x1b\n" +
	"\tsite_name\x18\x02 \x01(\tR\bsiteName\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\x126\n" +
	"\acookies\x18\x04 \x03(\v2\x1c.sessionproxy.v1.CookieInputR\acookies\x123\n" +
	"\x06tokens\x18\x05 \x03(\v2\x1b.sessionproxy.v1.TokenInputR\x06tokens\"m\n" +
	"\x15ImportSessionResponse\x12.\n" +
	"\x13original_session_id\x18\x01 \x01(\tR\x11originalSessionId\x12$\n" +
	"\x0etarget_site_id\x18\x02 \x01(\tR\ftargetSiteId2o\n" +
	"\rImportService\x12^\n" +
	"\rImportSession\x12%.sessionproxy.v1.ImportSessionRequest\x1a&.sessionproxy.v1.ImportSessionResponseB,Z*sessionproxy/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_sessionproxy_v1_import_proto_rawDescOnce sync.Once
	file_sessionproxy_v1_import_proto_rawDescData []byte
)

func file_sessionproxy_v1_import_proto_rawDescGZIP() []byte {
	file_sessionproxy_v1_import_proto_rawDescOnce.Do(func() {
		file_sessionproxy_v1_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessionproxy_v1_import_proto_rawDesc), len(file_sessionproxy_v1_import_proto_rawDesc)))
	})
	return file_sessionproxy_v1_import_proto_rawDescData
}

var file_sessionproxy_v1_import_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sessionproxy_v1_import_proto_goTypes = []any{
	(*CookieInput)(nil),           // 0: sessionproxy.v1.CookieInput
	(*TokenInput)(nil),            // 1: sessionproxy.v1.TokenInput
	(*ImportSessionRequest)(nil),  // 2: sessionproxy.v1.ImportSessionRequest
	(*ImportSessionResponse)(nil), // 3: sessionproxy.v1.ImportSessionResponse
}
var file_sessionproxy_v1_import_proto_depIdxs = []int32{
	0, // 0: sessionproxy.v1.ImportSessionRequest.cookies:type_name -> sessionproxy.v1.CookieInput
	1, // 1: sessionproxy.v1.ImportSessionRequest.tokens:type_name -> sessionproxy.v1.TokenInput
	2, // 2: sessionproxy.v1.ImportService.ImportSession:input_type -> sessionproxy.v1.ImportSessionRequest
	3, // 3: sessionproxy.v1.ImportService.ImportSession:output_type -> sessionproxy.v1.ImportSessionResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sessionproxy_v1_import_proto_init() }
func file_sessionproxy_v1_import_proto_init() {
	if File_sessionproxy_v1_import_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessionproxy_v1_import_proto_rawDesc), len(file_sessionproxy_v1_import_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sessionproxy_v1_import_proto_goTypes,
		DependencyIndexes: file_sessionproxy_v1_import_proto_depIdxs,
		MessageInfos:      file_sessionproxy_v1_import_proto_msgTypes,
	}.Build()
	File_sessionproxy_v1_import_proto = out.File
	file_sessionproxy_v1_import_proto_goTypes = nil
	file_sessionproxy_v1_import_proto_depIdxs = nil
}
