// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Layout wraps every dashboard page. htmx is loaded from a CDN rather than
// vendored - this is an internal owner tool, not a public-facing site
// where that would be a privacy/CSP concern worth avoiding.
func Layout(title string, loggedIn bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/transport/webui/templates/layout.templ`, Line: 12, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - SessionProxy</title><script src=\"https://unpkg.com/htmx.org@1.9.12\"></script><style>\n\t\t\t\t:root { color-scheme: dark; }\n\t\t\t\tbody { background:#0d1117; color:#c9d1d9; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; margin:0; }\n\t\t\t\ta { color:#58a6ff; text-decoration:none; }\n\t\t\t\tnav { display:flex; align-items:center; gap:1.5rem; padding:0.9rem 1.5rem; background:#161b22; border-bottom:1px solid #21262d; }\n\t\t\t\tnav .brand { font-weight:600; color:#c9d1d9; }\n\t\t\t\tmain { max-width:960px; margin:2rem auto; padding:0 1.5rem; }\n\t\t\t\ttable { width:100%; border-collapse: collapse; margin-top:1rem; }\n\t\t\t\tth, td { text-align:left; padding:0.5rem 0.75rem; border-bottom:1px solid #21262d; font-size:0.9rem; }\n\t\t\t\tth { color:#8b949e; font-weight:500; }\n\t\t\t\t.badge { padding:0.15rem 0.5rem; border-radius:999px; font-size:0.75rem; font-weight:600; }\n\t\t\t\t.badge-active { background:#0f3d21; color:#3fb950; }\n\t\t\t\t.badge-terminated { background:#3d1418; color:#f85149; }\n\t\t\t\tform { display:flex; flex-direction:column; gap:0.75rem; max-width:420px; }\n\t\t\t\tinput, textarea { background:#0d1117; border:1px solid #30363d; color:#c9d1d9; padding:0.5rem; border-radius:6px; font-size:0.9rem; }\n\t\t\t\tbutton { background:#238636; color:white; border:none; padding:0.5rem 1rem; border-radius:6px; cursor:pointer; font-size:0.9rem; }\n\t\t\t\tbutton.danger { background:#da3633; }\n\t\t\t\t.card { background:#161b22; border:1px solid #21262d; border-radius:8px; padding:1.25rem; margin-bottom:1rem; }\n\t\t\t\t.feed-item { padding:0.5rem 0; border-bottom:1px solid #21262d; font-size:0.85rem; }\n\t\t\t\t.muted { color:#8b949e; }\n\t\t\t</style></head><body><nav><span class=\"brand\">SessionProxy</span> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if loggedIn {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a href=\"/dashboard/links\">Links</a> <a href=\"/dashboard/import\">Import session</a> <a href=\"/dashboard/security-feed\">Security feed</a> <span style=\"flex:1\"></span> <a href=\"/dashboard/logout\">Log out</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</nav><main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
